version: '3.8'

services:
  # --- 1. KEYCLOAK (Spostato su 8180) ---
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: mensa-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      
      # --- CONFIGURAZIONE RETE (Corretta) ---
      # Abilita HTTP (niente HTTPS in locale)
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      
      KC_HOSTNAME_URL: http://localhost:8180     
      
      
      KC_PROXY: edge
    ports:
      # Mappa la porta 8180 del tuo PC alla 8080 del container
      - "8180:8080" 
    volumes:
      - ./dati_keycloak:/opt/keycloak/data/

  # --- 2. MONGODB ---
  mongodb:
    image: mongo:latest
    container_name: mensa-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # --- 3. MONGO EXPRESS ---
  mongo-express:
    image: mongo-express
    container_name: mensa-mongo-admin
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      # Ho rimosso KC_HOSTNAME_URL da qui, non c'entrava con Mongo Express
    ports:
      - "8082:8081"
    depends_on:
      - mongodb

volumes:
  mongo_data:
  # Ho rimosso ldap_data e ldap_config perché non li usiamo più